import tkinter 
from tkinter import *
from tkinter import messagebox
import pymysql
from tkinter import ttk
def showregistrationupdate():

    t=tkinter.Tk()
    t.geometry('700x700')
    t.title('registration')
    t.config(bg='green')
    r=Label(t,text='Registration Update Form',font=('arial',20),fg='black',bg='white')
    r.place(x=120,y=10)
    
    def updatedata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='institutemanagement')
        cur=db.cursor()
        xa=int(e1.get())
        xb=e2.get()
        xc=e3.get()
        xd=e4.get()
        xe=e5.get()
        xf=e6.get()
        xg=e7.get()
        xh=e8.get()
        xi=e9.get()
        sql="update registration set name='%s',address='%s',email='%s',phone='%s',courseid='%s',batchid='%s',feeplanid='%s',scholarshipid='%s' where regno=%d"%(xb,xc,xd,xe,xf,xg,xh,xi,xa)
        cur.execute(sql)
        db.commit()
        messagebox.showinfo('hi','done')
        e1.delete(0,END)
        e2.delete(0,END)
        e3.delete(0,END)
        e4.delete(0,END)
        e5.delete(0,END)
        e6.delete(0,END)
        e7.delete(0,END)
        e8.delete(0,END)
        e9.delete(0,END)
    def finddata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='institutemanagement')
        cur=db.cursor()
        xa=int(e1.get())
        sql="select name,address,email,phone,courseid,batchid,feeplanid,scholarshipid  from registration where regno=%d" %(xa)
        cur.execute(sql)
        data=cur.fetchone()
        e2.insert(0,data[0])
        e3.insert(0,data[1])
        e4.insert(0,data[2])
        e5.insert(0,data[3])
        e6.insert(0,data[4])
        e7.insert(0,data[5])
        e8.insert(0,data[6])
        e9.insert(0,data[7])
        
    def filldata():
         db=pymysql.connect(host='localhost',user='root',password='root',database='institutemanagement')
         cur=db.cursor()
         sql="select regno from registration"
         cur.execute(sql)
         m=[]
         data=cur.fetchall()
         for r in data:
             m.append(r[0])
         db.close()
         e1['values']=m
    
        
    a=Label(t,text='regno',bg='white')
    a.place(x=50,y=50)
    e1=ttk.Combobox(t)
    e1['values']
    e1.place(x=400,y=50)
    b=Label(t,text='name',bg='white')
    b.place(x=50,y=90)
    e2=Entry(t,width=20)
    e2.place(x=400,y=90)
    c=Label(t,text='address',bg='white')
    c.place(x=50,y=130)
    e3=Entry(t,width=20)
    e3.place(x=400,y=130)
    d=Label(t,text='email',bg='white')
    d.place(x=50,y=170)
    e4=Entry(t,width=20)
    e4.place(x=400,y=170)
    e=Label(t,text='phone',bg='white')
    e.place(x=50,y=210)
    e5=Entry(t,width=20)
    e5.place(x=400,y=210)
    f=Label(t,text='courseid',bg='white')
    f.place(x=50,y=250)
    e6=Entry(t,width=20)
    e6.place(x=400,y=250)
    g=Label(t,text='batchid',bg='white')
    g.place(x=50,y=300)
    e7=Entry(t,width=20)
    e7.place(x=400,y=300)
    i=Label(t,text='feeplanid',bg='white')
    i.place(x=50,y=350)
    e8=Entry(t,width=20)
    e8.place(x=400,y=350)
    h=Label(t,text='scholarshipid',bg='white')
    h.place(x=50,y=400)
    e9=Entry(t,width=20)
    e9.place(x=400,y=400)
    b1=Button(t,text='find',bg='green',command=finddata,width=20)
    b1.place(x=50,y=450)
    b2=Button(t,text='update',command=updatedata,bg='blue',width=20)
    b2.place(x=250,y=450)
    filldata()
    t.mainloop()