import tkinter
from tkinter import*
from tkinter import messagebox
import pymysql
def showregistrationsave():
    
    t=tkinter.Tk()
    t.geometry ('700x700')
    t.title('registration')
    t.config(bg='green')
    r=Label(t,text='Registration Save Form',font=('arial',20),fg='black',bg='white')
    r.place(x=120,y=10)
    
    def savedata():
        db=pymysql.connect(host='localhost',user='root',password='root',database='institutemanagement')
        cur=db.cursor()
        xa=int(e1.get())
        xb=e2.get()
        xc=e3.get()
        xd=e4.get()
        xe=e5.get()
        xf=e6.get()
        xg=e7.get()
        xh=e8.get()
        xi=e9.get()
        sql="insert into registration values (%d,'%s','%s','%s','%s','%s','%s','%s','%s')" % (xa,xb,xc,xd,xe,xf,xg,xh,xi)
        cur.execute(sql)
        db.commit()
        messagebox.showinfo('Hi','Saved')
        e1.delete(0,END)
        e2.delete(0,END)
        e3.delete(0,END)
        e4.delete(0,END)
        e5.delete(0,END)
        e6.delete(0,END)
        e7.delete(0,END)
        e8.delete(0,END)
        e9.delete(0,END)
    a=Label(t,text='regno',bg='white')
    a.place(x=50,y=50)
    e1=Entry(t,width=20)
    e1.place(x=400,y=50)
    b=Label(t,text='name',bg='white')
    b.place(x=50,y=90)
    e2=Entry(t,width=20)
    e2.place(x=400,y=90)
    c=Label(t,text='address',bg='white')
    c.place(x=50,y=130)
    e3=Entry(t,width=20)
    e3.place(x=400,y=130)
    d=Label(t,text='email',bg='white')
    d.place(x=50,y=170)
    e4=Entry(t,width=20)
    e4.place(x=400,y=170)
    e=Label(t,text='phone',bg='white')
    e.place(x=50,y=210)
    e5=Entry(t,width=20)
    e5.place(x=400,y=210)
    f=Label(t,text='courseid',bg='white')
    f.place(x=50,y=250)
    e6=Entry(t,width=20)
    e6.place(x=400,y=250)
    g=Label(t,text='batchid',bg='white')
    g.place(x=50,y=300)
    e7=Entry(t,width=20)
    e7.place(x=400,y=300)
    i=Label(t,text='feeplanid',bg='white')
    i.place(x=50,y=350)
    e8=Entry(t,width=20)
    e8.place(x=400,y=350)
    h=Label(t,text='scholarshipid',bg='white')
    h.place(x=50,y=400)
    e9=Entry(t,width=20)
    e9.place(x=400,y=400)
    b1=Button(t,text='Save',bg='green',command=savedata,width=20)
    b1.place(x=50,y=450)
    t.mainloop()
